/**
 * Données du Passeport Fidélité Viteos
 */

window.VITEOS_DATA = {
  initialUser: {
    name: "Jean-Félicien Martigny",
    points: 0,
    maxPointsTier: 150,
    trophies: [
      { id: "t1", title: "Fête des vendanges", date: "Septembre 2026", active: true },
      { id: "t2", title: "Playoffs NUC - Match #1", date: "Mars 2026", active: true },
      { id: "t3", title: "Saison 2026/27 - HCC", date: "Janvier 2026", active: true }
    ],
    scannedEvents: ["evt1"],
    claimedRewards: []
  },

  events: [
    {
      id: "evt1",
      title: "Fête des vendanges 2026",
      date: "4 - 5 septembre 2026",
      location: "Neuchâtel",
      pointsReward: 30
    },
    {
      id: "evt2",
      title: "HCC - HC Ajoie",
      date: "26 septembre 2026",
      location: "La Chaux-de-Fonds",
      pointsReward: 30
    },
    {
      id: "evt3",
      title: "NUC - Colombier",
      date: "12 septembre 2026",
      location: "Neuchâtel",
      pointsReward: 30
    },
    {
      id: "evt4",
      title: "Braderie de CDF",
      date: "30 septembre 2026",
      location: "La Chaux-de-Fonds",
      pointsReward: 30
    }
  ],

  // Liste complète des commerces partenaires acceptant les bons CID
  cidPartners: [
    "A La Grappe d'Or",
    "Acuitis SA",
    "Adrenalina Ski & Fun",
    "Aeschlimann Electromécanique",
    "Alpify Group Sàrl",
    "ApérO'Clock",
    "Atelier et boutique « au c cédille »",
    "Atelier Léa Parmigiani",
    "Au Grain d'Orge",
    "Au Grand-Bourgeau",
    "AU MOKA artisan torréfacteur cafés et thés",
    "Au petit bonheur",
    "Aux Goûts d'Angèle",
    "Aux paniers gourmands",
    "Babor Beauty SPA",
    "Bar Le Charlot",
    "Benu pharmacie Fleurier",
    "Berdoz Optic",
    "Bezençon Boissons",
    "Biedermann Bis",
    "Bijouterie et Horlogerie Michaud",
    "Bijouterie Le Diamant",
    "Bijoux Concept",
    "Bistrot Chauffage compris",
    "Boucherie Alves",
    "Boucherie Au Gourmet",
    "Boucherie Bohren",
    "Boucherie chez Denis",
    "Boucherie Chez Jeanneret",
    "Boucherie Christen Delicatessen",
    "Boucherie Gaille",
    "Boucherie Léger – Saint-Blaise",
    "Boucherie Margot",
    "Boucherie Schneiter",
    "Boucherie-Chacturerie de la Prairie",
    "Boucherie-Charcuterie Nicolet",
    "Boucherie-Traiteur de la Fontaine",
    "Boulangerie de la Dîme",
    "Boulangerie Mäder",
    "Boulangerie Vuissoz",
    "Bouquet d'Amour",
    "Boutique Benetton",
    "Boutique Caprice",
    "Boutique Catherine A.",
    "Boutique Chantal",
    "Boutique Chess",
    "Boutique du Livre",
    "Boutique Happiness DCO",
    "Boutique kado",
    "Boutique Macadam",
    "Boutique Mary-Claire",
    "Boutique Terre & Eau",
    "Briqu'à Loris",
    "Bucher et Walt SA",
    "Carrosserie de Boudry Vicario SA",
    "Carrosserie OES",
    "Centre de couture Bernina",
    "Cérès autrement",
    "Charlott' lingerie et prêt-à-porter",
    "Chez Lise",
    "Chez smoke",
    "Chez Steffy, laiterie de Fleurier",
    "Chocolaterie & Biscuiterie Christophe Sàrl",
    "Chocolaterie Walder Sàrl",
    "Chocolats RêvéPassion",
    "Coiffure Evolutif",
    "Coiffure Femina Tiffounet",
    "Comme une fleur",
    "Confiserie Schmid",
    "Confiserie Wodey-Suchard",
    "Coopérative Aux Mots Passants",
    "Coopérative des Halles",
    "Copy Service&bureautique Sàrl",
    "Cordonnerie de Neuchâtel",
    "Côté Ambiance",
    "Croisitour Voyages",
    "db donna",
    "Denner Express",
    "Denner Satellite – Epicerie des Arêtes Sàrl Robin Alfred",
    "DESSANGE Paris",
    "Dick Optique",
    "Discountvape",
    "DOUCE HEURE institut de beauté et de bien-être",
    "Droguerie de Fleurier",
    "Droguerie Schneitter",
    "Du Pain Ô Chocolat by Mitaillé",
    "Dubois Quincaillerie SA",
    "EA Kiosque",
    "ebPROmotion",
    "Ecopharma",
    "Envie de voir",
    "Epicerie de la Côte-aux-Fées / Eric Vuissoz",
    "Espace Optique",
    "Evolution Notebook Sàrl",
    "Fielmann",
    "Fornachon Appareils Ménagers",
    "Franchon Electroménager et Cuisines Sàrl",
    "Frédy Marti & Fils SA",
    "Frey Fleuristes",
    "Frutiger Mode",
    "Histoire de Fleurs",
    "impactmedias – La Chaux-de-Fonds",
    "impactmedias – Neuchâtel",
    "Imprimerie Monney Service",
    "In Vino Veritas",
    "Institut beauté Mon Paradis",
    "Institut BellArte",
    "Jacky Ducommun",
    "Jacot Haute chocolaterie",
    "Jolis mômes la boutique",
    "Kiosque du Seyon",
    "L'âme verte",
    "L'Épicerie de Marie",
    "L'Orchidée",
    "L'Organic",
    "La [kaban]",
    "La Bicycletterie Suisse",
    "La Boîte à cirage",
    "La Croisette",
    "La Croustille",
    "La Fab'Brique",
    "La Magie du Naturel",
    "La Maison de la Bible",
    "La maison du fromage Sterchi",
    "La Mobilière",
    "La Source du Salami S.Zanetta succ. Orlando",
    "La Tchauxtex",
    "Labtraiteur da Michele",
    "Laiterie de Savagnier",
    "Le Labo",
    "Le LOFT coiffure",
    "Le P'Tit Mag",
    "Le P'tit mag de Val",
    "le Silo",
    "Leroy Opticiens",
    "Les Thés du Marché Sàrl",
    "Librarie Le Rat Conteur",
    "Lunalo",
    "Mademoiselle Ö",
    "Magasin Denner (Dennis SA)",
    "Maison Cordey S.A.",
    "Marché Discount ABC",
    "Maroquinerie Biedermann SA",
    "Masserey Intérieur SA",
    "MATHILDA LOVES SHOES",
    "Medi-lum Sàrl",
    "Mercerie & Boutique du Temple Ch. & F. Messerli",
    "Mercerie Au petit Bonheur Sàrl",
    "Messmer Orthopédie",
    "Meubles Leitenberg",
    "MGPerf sarl",
    "Migrolino & Migrol Service",
    "mlb – stores for men",
    "Montres et Bijoux Robert",
    "My Styl",
    "New Griffon",
    "Novoptic",
    "Odac Meubles",
    "Œnothèque Chauffage compris",
    "Optic 2000",
    "Opticien Visilab",
    "Optique des Arcades P. et M-A. Lamboley",
    "Optique Gargantini",
    "outilplus Sàrl",
    "P!nk Cactus",
    "Papeterie La Plume Enchantée",
    "Payot Libraire La Chaux-de-Fonds",
    "Payot Libraire Neuchâtel",
    "Petite Manie",
    "Pharmacie Amavita Poste Le Locle",
    "Pharmacie Amavita Tripet",
    "Pharmacie Centrale de Boudry",
    "Pharmacie Centrale LCF S.A.",
    "Pharmacie de l'Hôtel-de-Ville",
    "Pharmacie de l'Orangerie",
    "Pharmacie de la Gare",
    "PHARMACIE des 3 CHEVRONS",
    "Pharmacie des Forges",
    "Pharmacie du Casino Le Locle SA",
    "Pharmacie du Château",
    "Pharmacie du Versoix",
    "Pharmacie Gauchat",
    "Pharmacie Littoral Centre",
    "Pharmacie MARIOTTI",
    "Pharmacie Marti | Cernier",
    "Pharmacie Marti | Place Pury",
    "Pharmacie Marti | Vauseyon",
    "Pharmacie Pillonel",
    "Pharmacie Plus Bourquin",
    "Pharmacie Plus Centrale",
    "Pharmacie Plus du Bourg",
    "Pharmacieplus Centrale Matthys SA",
    "Pharmacieplus de Colombier",
    "Pharmacieplus du Val-de-Travers",
    "Pierrot Ménager",
    "Poulpito Neuchâtel",
    "Premier Sous Sol",
    "Prétôt SA",
    "Prim'Heure, Donzé",
    "Pro Neige Sports",
    "Quincaillerie – Jaquet",
    "Quincaillerie du Château",
    "Quincaillerie Kaufmann & Fils",
    "Reysus Gérance SA",
    "RobEbike",
    "Rose Garden",
    "Royal Pêche",
    "Schindelholz J.-D. SA",
    "Schurch & Asco SA",
    "Siegenthaler & Choffet SA",
    "Stämpfli Thierry",
    "Station service Le Reymond Sàrl",
    "Stehlin Opticiens",
    "Swiss Bedding – Dormez comme sur des nuages",
    "TCS Section Neuchâtel",
    "Team Ginette Coiffure sàrl",
    "Toulefer SA",
    "Tribu Sàrl communication & relations publiques",
    "val impression",
    "ValFood-Import Sàrl",
    "Veripharm SA Pharmacie Les Ponts-de-Martel",
    "Vertical Passion",
    "Vinothèque de la Charrière SA",
    "Vinothèque de la Charrières SA",
    "Vito Viande",
    "XRP Photo",
    "Zâman Sarl"
  ],

  seasonalCatalog: {
    winter: [
      {
        id: "w1",
        title: "Chaussettes chaudes en laine",
        subtitle: "Laine recyclée suisse",
        points: 150,
        image: "assets/socks.png"
      },
      {
        id: "w2",
        title: "Sablier de douche 4 minutes",
        subtitle: "Économie d'eau chaude",
        points: 150,
        image: "assets/hourglass.png"
      },
      {
        id: "w3",
        title: "Couvre-selle de vélo imperméable",
        subtitle: "Protection selle durable",
        points: 150,
        image: "assets/selle.png"
      },
      {
        id: "w4",
        title: "Bon 20 CHF Commerces Neuchâtel (CID)",
        subtitle: "Artisans et commerces locaux",
        points: 250,
        image: "assets/bons.png",
        hasInfo: true
      },
      {
        id: "w5",
        title: "Billet Match HCC - Patinoire des Mélèzes",
        subtitle: "Place assise",
        points: 300
      }
    ],
    summer: [
      {
        id: "s2",
        title: "Protège-gobelet",
        subtitle: "Silicone réutilisable",
        points: 150
      },
      {
        id: "s4",
        title: "Entrée Piscine du Nid-du-Crô",
        subtitle: "Piscine de Neuchâtel",
        points: 180
      },
      {
        id: "s5",
        title: "Billet Match NUC Volleyball - La Riveraine",
        subtitle: "Match championnat LNA",
        points: 250
      }
    ]
  },

  // 5 points par question = 25 points par quiz complet
  quizQuestions: [
    {
      id: "q1",
      category: "Énergie",
      question: "Quelle est la part d'électricité renouvelable distribuée par Viteos dans le canton de Neuchâtel ?",
      options: [
        { text: "Environ 35%", isCorrect: false },
        { text: "Plus de 80% (Hydro, Solaire & Éolien)", isCorrect: true },
        { text: "50% exactement", isCorrect: false },
        { text: "15% seulement", isCorrect: false }
      ],
      rewardPoints: 5
    },
    {
      id: "q2",
      category: "Sport",
      question: "Quel club féminin de volleyball évolue à la salle de la Riveraine à Neuchâtel ?",
      options: [
        { text: "Volley Lugano", isCorrect: false },
        { text: "Viteos NUC Volleyball", isCorrect: true },
        { text: "Genève Volley", isCorrect: false },
        { text: "Sm'Aesch Pfeffingen", isCorrect: false }
      ],
      rewardPoints: 5
    },
    {
      id: "q3",
      category: "Éco-gestes",
      question: "Réduire sa douche de 10 à 4 minutes grâce à un sablier permet d'économiser environ :",
      options: [
        { text: "2 à 3 litres d'eau", isCorrect: false },
        { text: "Jusqu'à 40 à 60 litres d'eau chaude", isCorrect: true },
        { text: "10 litres d'eau", isCorrect: false },
        { text: "Aucune différence", isCorrect: false }
      ],
      rewardPoints: 5
    },
    {
      id: "q4",
      category: "Hockey",
      question: "Dans quelle patinoire évolue le Hockey Club La Chaux-de-Fonds (HCC) ?",
      options: [
        { text: "La Patinoire des Mélèzes", isCorrect: true },
        { text: "La Vaudoise aréna", isCorrect: false },
        { text: "PostFinance Arena", isCorrect: false },
        { text: "BCF Arena", isCorrect: false }
      ],
      rewardPoints: 5
    },
    {
      id: "q5",
      category: "Vision",
      question: "Pourquoi Viteos remplace les goodies jetables lors des événements ?",
      options: [
        { text: "Pour réduire les déchets et privilégier des objets durables", isCorrect: true },
        { text: "Rupture de stock plastique", isCorrect: false },
        { text: "Arrêt des partenariats", isCorrect: false },
        { text: "Simple changement de couleur", isCorrect: false }
      ],
      rewardPoints: 5
    }
  ]
};
